DarkElfNames = {
  --------------FEMALE FIRSTNAMES
    {
      Name = "Alarion",
      Gender = "Female",
      Type = "FirstName",
      Suffixes = {},
      Prefixes = {},
    },
    {
      Name = "Hulaylian",
      Gender = "Female",
      Type = "FirstName",
      Suffixes = {},
      Prefixes = {},
    },
    
    {
      Name = "Millen",
      Gender = "Male",
      Type = "FirstName",
      Suffixes = {},
      Prefixes = {},
    },
    {
      Name = "Koval",
      Gender = "Male",
      Type = "FirstName",
      Suffixes = {"a",},
      Prefixes = {},
    },
    --------------SUNAMES
    {
      Name = "Soulblaze",
      Gender = "Both",
      Type = "Surname",
      Suffixes = {"r",},
      Prefixes = {},
    },
    {
      Name = "Darkpath",
      Gender = "Both",
      Type = "Surname",
      Suffixes = {},
      Prefixes = {},
    },
    {
      Name = "Pyrebane",
      Gender = "Both",
      Type = "Surname",
      Suffixes = {},
      Prefixes = {},
    },
    {
      Name = "Hellbleed",
      Gender = "Both",
      Type = "Surname",
      Suffixes = {"er",},
      Prefixes = {},
    },
    {
      Name = "Shadowripper",
      Gender = "Both",
      Type = "Surname",
      Suffixes = {},
      Prefixes = {},
    },
    {
      Name = "Warreaper",
      Gender = "Both",
      Type = "Surname",
      Suffixes = {},
      Prefixes = {},
    },
    {
      Name = "Duskbind",
      Gender = "Both",
      Type = "Surname",
      Suffixes = {"er",},
      Prefixes = {},
    },
    {
      Name = "gloomgrip",
      Gender = "Both",
      Type = "Surname",
      Suffixes = {"er",},
      Prefixes = {},
    },
    {
      Name = "Deadarrow",
      Gender = "Both",
      Type = "Surname",
      Suffixes = {},
      Prefixes = {},
    },
    {
      Name = "Shadowfall",
      Gender = "Both",
      Type = "Surname",
      Suffixes = {},
      Prefixes = {},
    },
  }