DarkElfNames = {
  --------------FIRSTNAMES
    {
      Name = "Alarion",
      Gender = "Female",
      Type = "FirstName",
      Suffixes = {},
      Prefixes = {},
    },
    {
      Name = "Nerlash",
      Gender = "Female",
      Type = "FirstName",
      Suffixes = {},
      Prefixes = {},
    },
    {
      Name = "Nhetta",
      Gender = "Female",
      Type = "FirstName",
      Suffixes = {},
      Prefixes = {},
    },
    {
      Name = "Hulaylian",
      Gender = "Female",
      Type = "FirstName",
      Suffixes = {},
      Prefixes = {},
    },
    {
      Name = "Vovhash",
      Gender = "Female",
      Type = "FirstName",
      Suffixes = {},
      Prefixes = {},
    },
    {
      Name = "Heva",
      Gender = "Female",
      Type = "FirstName",
      Suffixes = {},
      Prefixes = {},
    },
    
    {
      Name = "Millen",
      Gender = "Male",
      Type = "FirstName",
      Suffixes = {},
      Prefixes = {},
    },
    {
      Name = "Koval",
      Gender = "Male",
      Type = "FirstName",
      Suffixes = {"a",},
      Prefixes = {},
    },
    {
      Name = "Narol",
      Gender = "Male",
      Type = "FirstName",
      Suffixes = {},
      Prefixes = {},
    },
    {
      Name = "Delur",
      Gender = "Male",
      Type = "FirstName",
      Suffixes = {},
      Prefixes = {},
    },
    {
      Name = "Vigic",
      Gender = "Male",
      Type = "FirstName",
      Suffixes = {},
      Prefixes = {},
    },
    {
      Name = "Nauker",
      Gender = "Male",
      Type = "FirstName",
      Suffixes = {},
      Prefixes = {},
    },

    --------------SUNAMES
    {
      Name = "Soulblaze",
      Gender = "Both",
      Type = "Surname",
      Suffixes = {"r",},
      Prefixes = {},
    },
    {
      Name = "Darkpath",
      Gender = "Both",
      Type = "Surname",
      Suffixes = {},
      Prefixes = {},
    },
    {
      Name = "Pyrebane",
      Gender = "Both",
      Type = "Surname",
      Suffixes = {},
      Prefixes = {},
    },
    {
      Name = "Hellbleed",
      Gender = "Both",
      Type = "Surname",
      Suffixes = {"er",},
      Prefixes = {},
    },
    {
      Name = "Shadowripper",
      Gender = "Both",
      Type = "Surname",
      Suffixes = {},
      Prefixes = {},
    },
    {
      Name = "Warreaper",
      Gender = "Both",
      Type = "Surname",
      Suffixes = {},
      Prefixes = {},
    },
    {
      Name = "Duskbind",
      Gender = "Both",
      Type = "Surname",
      Suffixes = {"er",},
      Prefixes = {},
    },
    {
      Name = "Gloomgrip",
      Gender = "Both",
      Type = "Surname",
      Suffixes = {"er",},
      Prefixes = {},
    },
    {
      Name = "Deadarrow",
      Gender = "Both",
      Type = "Surname",
      Suffixes = {},
      Prefixes = {},
    },
    {
      Name = "Shadowfall",
      Gender = "Both",
      Type = "Surname",
      Suffixes = {},
      Prefixes = {},
    },
  }