DarkElfSpecialDistricts = {
    TheBlackTower = {
        Name = "The Black Tower",
        Type = "District",
        Population = 1,
        SupportedBackgrounds = {"Urban", },
        ExtraCareers = {"Servant", "Slave", },
        FactionTemplates = {},
        SpecialFactions = {},
        RulingFaction = {},
        SocialClassModifier = 20,
        ChildWebs = {},
        Districts = {},
    },
    BlackGuardTowers = {
        Name = "Black Guard Towers",
        Type = "District",
        Population = 1,
        SupportedBackgrounds = {"Urban", },
        ExtraCareers = {"Servant", "Slave", },
        FactionTemplates = {},
        SpecialFactions = {"BlackGuardFaction"},
        RulingFaction = {"BlackGuardFaction" },
        SocialClassModifier = 20,
        ChildWebs = {},
        Districts = {},
      },
}