DarkElfDistricts = {
  HarbourDistrict = {
    Name = "Harbour District",
    Type = "District",
    Population = 3,
    SupportedBackgrounds = {"Military", "Mercantile", "Slave", "Servant", "Nobility",},
    ExtraCareers = {},
    FactionTemplates = {"HarbourFaction", "BarracksFaction", },
    SpecialFactions = {},
    RulingFaction = {"HarbourFaction",},
    SocialClassModifier = 0,
  },
  NobleDistrict = {
    Name = "Noble District",
    Type = "District",
    Population = 3,
    SupportedBackgrounds = {"Military", "Mercantile", "Slave", "Servant", "Nobility", },
    ExtraCareers = {},
    FactionTemplates = {"NobilityFaction", "NobleFamilyFaction"},
    SpecialFactions = {},
    RulingFaction = {"NobilityFaction",},
    SocialClassModifier = 25,
  },
  SlaveDistrict = {
    Name = "Slave District",
    Type = "District",
    Population = 3,
    SupportedBackgrounds = {"Military", "Mercantile", "Slave", "Servant", "Nobility", },
    ExtraCareers = {},
    FactionTemplates = {"SlaversFaction", "BarracksFaction",},
    SpecialFactions = {},
    RulingFaction = {"SlaversFaction",},
    SocialClassModifier = 25,
  },
  TempleOfKhaineDistrict = {
    Name = "Temple Of Khaine District",
    Type = "District",
    Population = 3,
    SupportedBackgrounds = {"Military", "Slave", "Servant", "Nobility", },
    ExtraCareers = {},
    FactionTemplates = {},
    SpecialFactions = {},
    RulingFaction = {},
    SocialClassModifier = 25,
  },
  GuildsDistrict = {
    Name = "Guilds District",
    Type = "District",
    Population = 3,
    SupportedBackgrounds = {"Military", "Mercantile", "Slave", "Servant", "Nobility",},
    ExtraCareers = {},
    FactionTemplates = {"GuildFactions",},
    SpecialFactions = {},
    RulingFaction = {"GuildFactions",},
    SocialClassModifier = 25,
  },
  TheBlackHighway = {
    Name = "The Black Highway",
    Type = "District",
    Population = 3,
    SupportedBackgrounds = {"Rural", "Wanderer",},
    ExtraCareers = {},
    FactionTemplates = {},
    SpecialFactions = {},
    RulingFaction = {},
    SocialClassModifier = 25,
  },
}